### ISSUE TITLE
Binary Search in rotated array

### ISSUE THREAD

**Issue by ameer-w-ali** [adarshpand3y/Hacktoberfest2022-DSA#252]
Binary search in sorted but rotated array like
1 2 3 4 5 is sorted if this is also rotated at any point somewhat like 
4 5 1 2 3 then how binary search works. #

**Comment by Lavanyasuc31** [comment]
Hello , Please assign me this issue . I'll  add the detailed explanation along with the code

**Comment by Sushantkumarsingh01** [comment]
Please assign me this issue

**Comment by mohitkrsuman** [comment]
Can you assign this issue to me, I will solve this issue.

**Comment by rprithvi653** [comment]
Can you assign this issue to me, I will solve this issue.
