### ISSUE TITLE
Binary Search using c Programming

### ISSUE THREAD

**Issue by abhisek247767** [adarshpand3y/Hacktoberfest2022-DSA#43]
I would like to add Binary Search Code in C programming If You Give that opportunity.

**Comment by ankit-akash** [comment]
I just learned binary search using c and python and i can help u with that!

**Comment by Devanshu011** [comment]
I want to work on this

**Comment by var-rishabh** [comment]
I would like to add Binary Search Code in C programming in this repository.

Reasons to give me this opportunity.
- I add comments in every necessary line of code, so anyone can understand it's working.
- I use meaning variable and function names.
- I have read all of your guidelines so I'll push code without violating any of your rules.
- I write PRs with all necessary details in comments.

**Comment by Devanshu011** [comment]
Sir I have created file to your repository please check and merge it.

**Comment by abhisek247767** [comment]
But this repository excluded from Hackberfest2022 repository
