### ISSUE TITLE
I want to add a Guessing Game on C language

### ISSUE THREAD

**Issue by Ramank2002** [adarshpand3y/Hacktoberfest2022-DSA#5]
Hello Sir,
I am Raman Kumar Gupta, with GitHub Id - Ramank2002.
I want to contribute to your repo by adding a new Guessing Game written primarily in C Language.
Kindly consider it and I'll be very thankful to you.
Regards,
Raman Kumar Gupta

**Comment by Rishavgupta12345** [comment]
brother just make the pull request , don't create issues here
