### ISSUE TITLE
Binary Tree in java

### ISSUE THREAD

**Issue by saty-a** [adarshpand3y/Hacktoberfest2022-DSA#88]

**Comment by saty-a** [comment]
I would like to contribute to this issue. Can you assign this issue to me @adarshpand3y !!

**Comment by harika1314** [comment]
can you assign this issue to me

**Comment by yuvithakur007** [comment]
Can you assign me this issue? I would like to work on this.

**Comment by Rufus-paul** [comment]
can you assign this issue to me

**Comment by shraddhatech16** [comment]
sir, can you pls assign this issue to me?

**Comment by Bitan-Kundu** [comment]
Can you assign this issue to me?

**Comment by shaziaah19** [comment]
hello ,please assign this issue to me i am good at java

**Comment by snehasish-pathak** [comment]
**Sir, can you please assign this issue to me?**
